services:
  api-service:
    build:
      context: ${PROJECT_ROOT}/api-service
      dockerfile: Dockerfile
    container_name: api-service
    restart: always
    depends_on:
      - db-service
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_SERVICE_ADDR=:8010
      - API_SERVICE_ADDR=:8080
    volumes:
      - ${PROJECT_ROOT}/out/logs/api-service:/app/out/logs
    ports:
      - "8080:8080"

  db-service:
    build:
      context: ${PROJECT_ROOT}/db-service
      dockerfile: Dockerfile
    container_name: db-service
    restart: always
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_SERVICE_ADDR=:8010
    volumes:
      - ${PROJECT_ROOT}/out/logs/db-service:/app/out/logs
    ports:
      - "8010:8010"

  postgres:
    image: postgres:18-bookworm
    container_name: postgres
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: postgres-port-forwarder
    command: "tcp-listen:5432,fork,reuseaddr tcp-connect:postgres:5432"
    ports:
      - "127.0.0.1:5432:5432"

  postgres-migrate:
    image: migrate/migrate:v4.19.1
    container_name: postgres-migrate
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations
